version: "3.9"

services:
  # Milvus 向量資料庫
  etcd:
    container_name: roadmap_etcd
    image: quay.io/coreos/etcd:v3.5.5
    env_file:
      - ./database/config/etcd_conf.env
    volumes:
      - ./database/milvus_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - roadmap_network

  minio:
    container_name: roadmap_minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    env_file:
      - ./database/config/minio_conf.env
    volumes:
      - ./database/milvus_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - roadmap_network

  milvus:
    container_name: roadmap_milvus
    image: milvusdb/milvus:v2.3.4
    command: [ "milvus", "run", "standalone" ]
    env_file:
      - ./database/config/milvus_conf.env
    volumes:
      - ./database/milvus_data:/var/lib/milvus
    expose:
      - "19530"
      - "9091"
    # ports:
    #   - "19530:19530"
    #   - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - roadmap_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 15s

  milvus-init:
    build:
      context: ./database/milvus_data
      dockerfile: Dockerfile_MilvusInit
    container_name: milvus_init
    depends_on:
      milvus:
        condition: service_healthy
    networks:
      - roadmap_network
    volumes:
      - ./database/milvus_data:/init
      - ./database/milvus_data/JOB_embedding.csv:/init/JOB_embedding.csv
    command: >
      sh -c "python /init/init_milvus.py &&
            touch /init/.init_done"


volumes:
  etcd_data:
  minio_data:
  milvus_data:

networks:
  roadmap_network:
    external: true
