FROM postgres:16.3-alpine

# 複製初始化腳本
COPY ./init_script/*.sh /docker-entrypoint-initdb.d/
COPY ./init_csv/*.csv /data/
# 確保檔案權限
RUN chmod 777 /data
RUN chmod 777 /docker-entrypoint-initdb.d
RUN chmod +x /docker-entrypoint-initdb.d/*.sh
RUN chmod 666 /data/*.csv